import { EraData, EraId } from './types';

export const ERAS: EraData[] = [
  {
    id: EraId.OLD_EGYPT,
    name: "Old Kingdom",
    description: "Journey back to the time of Pharaohs and Pyramids (c. 2686–2181 BC).",
    previewImage: "/Old-Egypt-Preview.png", // Fallback placeholder
    promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing ancient Egyptian pharaonic outfits. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are fully dressed in regal pharaonic costumes with elegant gold and deep turquoise details and subtle hieroglyphic patterns. Lighting is warm and cinematic with realistic shadows and natural depth of field. The final image should look like a modern professional photoshoot with a strong pharaonic theme. No added accessories, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented image of a man transformed into an Ancient Egyptian pharaoh, where the subject’s facial features, skin tone, eye shape, facial structure, and overall identity are fully preserved and unchanged, and only the FACE is preserved while all clothing, accessories, and hairstyle are completely replaced. The subject wears authentic Ancient Egyptian royal attire with mandatory full outfit replacement, including a traditional white or cream linen shendyt (pleated kilt) secured with a gold ceremonial belt, a broad royal wesekh collar crafted from gold, lapis lazuli, turquoise, and carnelian covering the shoulders and upper chest, gold armlets and bracelets on both arms, and a straight ceremonial false beard with dark material and gold accents. The head is adorned with a structured Ancient Egyptian Nemes headdress in gold and deep blue stripes, sculptural and symmetrical in form, inspired by museum statues and relief carvings, resting naturally on the head without visible wrapping folds or fabric knots, clean geometric lines, regal and iconic. Traditional Ancient Egyptian male makeup is applied, including black kohl eyeliner from galena or stibnite defining the eyes, subtle green malachite eyeshadow, very light red ochre tint on lips and cheeks, and a natural matte skin finish, refined and historically accurate with no modern cosmetics. The pharaoh stands upright with a calm, powerful, and authoritative expression, regal posture, and dignified presence. The image is photorealistic with cinematic lighting, realistic linen and gold textures, soft shadows, shallow depth of field, no fantasy elements, no stylization, and no modern fashion influence. Background: {{BACKGROUND}}",
    singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of an Ancient Egyptian queen standing confidently. She wears a flowing white linen kalasiris gown with subtle translucency and refined gold trim that catches the light. She wears an ornate beaded queen-style headdress with intricate patterns, complemented by gold and gemstone bracelets, a broad collar, and ceremonial jewelry. Her makeup is authentic Ancient Egyptian: bold black kohl eyeliner and mascara from galena or stibnite, green malachite eyeshadow, subtle copper-gold highlights, red ochre on lips and cheeks, henna on nails, and naturally glowing, moisturized skin. Her facial features, skin tone, expression, and hair color are fully preserved and unchanged, reflecting her individuality. Background: {{BACKGROUND}}",
    backgrounds: [
      "the majestic Philae Temple beside the Nile River, with stone columns, statues of gods and goddesses, lush palm trees, flowering plants, soft mist rising from the river, and reflections on the water. The sky glows with warm golden-hour light, cinematic god rays, subtle cosmic particles, shallow depth of field, realistic shadows, and atmospheric fog. Photorealistic, majestic, sacred, and timeless.",
      "the Great Pyramids of Giza at sunset, with the Sphinx visible in the hazy distance. The desert sand glows with a golden hue, and the sky is a dramatic gradient of orange and purple. The atmosphere is ancient, mysterious, and grand, with a sense of eternal history.",
      "the massive columns of the Karnak Temple Hypostyle Hall, illuminated by torchlight and shafts of sunlight piercing through the stone roof. The walls are covered in hieroglyphs and relief carvings. The atmosphere is mystical, spiritual, and awe-inspiring.",
      "a luxurious royal palace interior with painted soaring columns, golden artifacts, and an open balcony overlooking the Nile. The walls are adorned with colorful frescoes of daily life and mythology. The floor is polished stone, reflecting the warm light of oil lamps.",
      "Luxor Temple at dusk, monumental statues and obelisks glowing under warm torchlight, ancient stone pathways leading through massive columns and gateways. The sky transitions into deep blues and purples, subtle mist and light bloom enhancing the sacred ambiance, cinematic lighting, spiritual, historic, and awe-inspiring.",
      "the Valley of the Kings nestled among dramatic desert cliffs, ancient rock-cut tomb entrances carved into golden limestone mountains, soft desert haze drifting through the valley. The sky is pale and expansive, sunlight washing over the terrain, subtle shadows and windblown sand creating a solemn, mysterious, and reverent atmosphere.",
      "the Temple of Hatshepsut rising in grand terraces against towering limestone cliffs, symmetrical colonnades and statues bathed in warm desert light. The scene is calm and majestic, with soft atmospheric haze, gentle shadows, muted earth tones, and a timeless sense of royal power and architectural harmony.",
      "the Abu Simbel Temples carved directly into a colossal sandstone cliff, massive seated statues of Ramses II illuminated by dramatic sunlight. The desert landscape is vast and silent, warm tones of sand and stone dominate the scene, subtle atmospheric haze, strong contrast lighting, monumental, powerful, and timeless."
    ],
    stamps: [
      "/Stamps/Old-Egyptian/1.png",
      "/Stamps/Old-Egyptian/2.png",
      "/Stamps/Old-Egyptian/3.png"
    ]
  },
  {
    id: EraId.COPTIC_EGYPT,
    name: "Coptic Era",
    description: "Experience the unique art and spirituality of late antique Egypt (c. 3rd–7th century AD).",
    previewImage: "/Coptic-Preview.png",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian man from the Coptic era of late antiquity, standing calmly and facing the camera. His facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.He wears an authentic Coptic linen tunic (kolothos) in natural off-white or beige tones, with historically accurate tapestry-woven clavi and orbiculi featuring subtle geometric or floral motifs in muted red, indigo, or ochre. The fabric appears hand-woven with visible linen texture and natural dyes, fitting modestly and realistically.His grooming is natural and understated: short dark hair, optional trimmed beard, and minimal traditional kohl lightly defining the eyes in a historically accurate manner. No crowns, jewelry, pharaonic elements, or modern accessories.Lighting is warm and soft, with realistic shadows and shallow depth of field, resembling a modern professional portrait while maintaining an authentic ancient Coptic Egyptian atmosphere. Skin texture is natural and lifelike.Background: {{BACKGROUND}}"
    , singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian woman from the Coptic era of late antiquity, standing gracefully and facing the camera. Her facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.She wears an authentic Coptic linen tunic in natural linen or soft earth tones, decorated with tapestry-woven clavi and orbiculi featuring delicate geometric or floral patterns in muted red, indigo, or gold-ochre hues. A historically accurate light mantle or veil may be draped naturally over the shoulders or head, consistent with early Christian Egyptian customs. The fabric appears hand-woven, with visible linen texture and natural dyes.Her appearance is modest and natural: minimal makeup, softly defined eyes with subtle traditional kohl, natural lips, and historically appropriate hairstyle partially covered by the veil. No jewelry beyond simple, era-accurate details; no crowns or modern elements.Lighting is warm and soft with realistic shadows and gentle depth of field, creating a refined modern portrait aesthetic grounded in authentic ancient Coptic Egyptian styling. Skin texture is natural and realistic.Background: {{BACKGROUND}}"
    , promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing traditional Coptic Egyptian clothing from late antiquity. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are dressed in authentic Coptic garments, including woven linen tunics (kolothos) with tapestry-woven decorative clavi and orbiculi, geometric and floral motifs, earthy beige and natural linen tones, and hand-embroidered borders. Optional shawls, mantles, or veils may appear depending on gender and era, but must remain historically accurate to early Christian Egypt. Textures should show real linen weave and natural dyes.Lighting is warm and soft with realistic shadows and natural depth of field, creating the look of a modern professional photoshoot with a strong ancient Coptic Egyptian theme. No added accessories outside historical context, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    backgrounds: [
      "an ancient Coptic monastery courtyard with limestone walls and desert plants. The sunlight is bright and harsh, casting deep shadows. The atmosphere is peaceful, ascetic, and timeless.",
      "a historic street in Old Cairo (Masr el Adima) with stone arches and hanging oil lamps. The narrow alleyway is bustling with subtle activity, although the focus remains on the subjects. The textures of the stone and wood are weathered and authentic.",
      "the interior of an ancient stone church with faded frescoes and warm candlelight. The air is thick with the scent of incense. The light is soft, golden, and mysterious, illuminating the faces of the subjects.",
      "the Religious Complex of Old Cairo (Masr el-Adima), with ancient stone church walls, arched entrances, wooden doors with iron fittings, and hanging oil lamps. Sunlight filters softly through narrow passages, casting long shadows on weathered limestone surfaces. The atmosphere is sacred, historic, and contemplative, with subtle incense haze and timeless stillness.",
      "the Hanging Church in Old Cairo, elevated above ancient stone towers, featuring carved wooden screens, Coptic crosses, marble columns, and softly glowing hanging lamps. Warm golden candlelight illuminates the interior, revealing aged frescoes and icons, with a peaceful, reverent, and spiritual atmosphere.",
      "the Monastery of Saint Simon the Tanner carved into the Mokattam cliffs, massive stone walls and amphitheater-like spaces hewn directly from the rock. Sunlight streams into the open sanctuary, illuminating carved crosses and simple stone surfaces. The scale is monumental yet humble, evoking devotion, endurance, and faith.",
      "the Church of Saint George (Mar Girgis) in Old Cairo, with its distinctive round stone structure, ancient brickwork, and wooden iconostasis. Soft daylight enters through small arched windows, highlighting worn stone textures and sacred silence. The atmosphere is solemn, historical, and deeply spiritual.",
      "Saint Catherine’s Monastery at the foot of Mount Sinai, surrounded by rugged granite mountains and desert terrain. Thick stone walls enclose the ancient complex, with cypress trees, simple courtyards, and a vast open sky above. The light is clear and crisp, the air pure, creating a feeling of isolation, holiness, and timeless monastic life."
    ],
    stamps: [
      "/Stamps/Coptic/1.png",
      "/Stamps/Coptic/2.png"
    ]
  },
  {
    id: EraId.ISLAMIC_EGYPT,
    name: "Islamic Golden Age",
    description: "Step into the vibrant culture of medieval Cairo (c. 7th–16th century AD).",
    previewImage: "./Islamic-Preview.png",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian man from the early Islamic period, standing calmly and facing the camera. His facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image. He wears historically accurate early Islamic Egyptian clothing: {{CLOTHING}} His grooming is natural and modest: short or medium dark hair, optional neatly kept beard, and no modern styling. No crowns, no jewelry outside historical context, and no contemporary accessories. Lighting is warm and cinematic with realistic shadows and natural depth of field, creating a modern professional portrait aesthetic grounded in early Islamic Egyptian culture. Skin texture is natural and lifelike. Background: {{BACKGROUND}}",
    singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian woman from the early Islamic period, standing gracefully and facing the camera. Her facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image. She wears historically accurate early Islamic Egyptian attire: {{CLOTHING}} Her appearance is modest and natural: minimal makeup, softly defined eyes, natural lips, and historically appropriate hairstyle. No modern accessories or jewelry beyond simple, era-appropriate details. Lighting is warm and cinematic with realistic shadows and gentle depth of field, producing a refined modern portrait feel while preserving authentic early Islamic Egyptian aesthetics. Skin texture is natural and realistic. Background: {{BACKGROUND}}",
    promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing traditional clothing from early Islamic Egypt. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are dressed in historically accurate garments, specifically: {{CLOTHING}} Colors should reflect natural dyes: soft whites, creams, deep blues, earthy reds, greens, and muted tones. Lighting is warm and cinematic with realistic shadows and natural depth of field, creating the look of a modern professional photoshoot with an early Islamic Egyptian cultural theme. No added accessories outside historical context, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    backgrounds: [
      "the Mosque of Amr ibn al-As in Old Cairo, featuring a vast open courtyard surrounded by arcades of simple stone columns and rounded arches. Soft morning sunlight pours across the marble floor, casting long rhythmic shadows. The atmosphere is calm, spiritual, and foundational, with gentle dust particles in the air and warm, natural illumination.",
      "the Citadel of Saladin overlooking Cairo, massive stone fortifications and defensive towers rising above the city. Golden-hour sunlight bathes the walls in warm amber tones, with dramatic shadows emphasizing the scale of the architecture. The sky is clear with subtle haze, creating a powerful, historic, and commanding atmosphere.",
      "the Mosque-Madrasa of Sultan Hassan, towering Mamluk architecture with monumental stone portals, soaring arches, and intricate geometric carvings. Shafts of sunlight descend from high windows, creating dramatic light beams and deep contrast. The atmosphere is majestic, awe-inspiring, and solemn, with cinematic volumetric lighting.",
      "the Mosque of Ibn Tulun with its vast open courtyard and spiral minaret, sunlit stone arcades forming repeating arches around the space. Late afternoon light casts soft golden tones across textured plaster walls, with long shadows and a sense of openness, serenity, and timeless Islamic simplicity.",
      "the Qalawun Complex on Al-Muizz Street, featuring richly decorated facades, carved stone details, and elegant arches. Warm lantern light mixes with fading daylight, creating a balanced glow of amber and soft blue tones. The atmosphere is intimate yet grand, historical, and vibrant, with subtle reflections and gentle atmospheric haze."
    ],
    stamps: [
      "/Stamps/Islamic/1.png",
      "/Stamps/Islamic/2.png",
      "/Stamps/Islamic/3.png",
      "/Stamps/Islamic/4.png"
    ],
    clothing: {
      men: [
        "Teal/emerald brocade long robe with subtle all-over pattern, high collar, gold embroidered trim along the center front and cuffs, wide bell sleeves. Wide geometric woven waist belt in teal and gold. Ivory-white draped sash/shoulder cloth wrapped across the torso and hanging long at the side. Cream-and-gold wrapped turban with a blue gemstone brooch, a white feather plume, and a small gold tassel.",
        "Ivory/off-white knee-length coat/kaftan with a clean front opening and structured shoulders. Pale blue embroidered V-shaped yoke/chest bib with delicate floral/arabesque motifs and small jewel accents. Sleeves feature blue embroidered panels near the elbows/cuffs with soft pink under-sleeves visible beneath. White inner tunic with loose white trousers. Wide ornate belt with a large decorative jewel buckle. Cream turban with a subtle pink stripe. Pointed cream boots.",
        "Chainmail hauberk with visible ring texture on sleeves and torso. Sleeveless maroon/dark red brocade surcoat/over-robe worn on top, with subtle woven motifs, gold edging, and vertical trim down the front; split skirt for movement. Gray under-tunic and gray trousers. Wide black leather belt with engraved metal fittings and an attached pouch; optional scabbard/sheath at the hip. Domed steel helmet with a small finial, worn over a white hood/neck wrap. Brown leather boots.",
        "Dark chocolate-brown velvet robe/kaftan with heavy gold embroidered trim along the front opening and hem. Ornate gold brocade sleeves with dense floral/arabesque patterns. Underlayers include a deep purple central panel/sash and a muted blue inner garment peeking at the hem. Cross-body multi-strand pearl harness forming an X across the chest with a large jeweled medallion centerpiece; matching jeweled waist belt. White wrapped turban with a red gemstone ornament and a tall white feather plume, with a subtle golden crown/halo-like detail."
      ],
      women: [
        "Floor-length deep red brocade/velvet gown with dense gold motifs and turquoise/teal embroidered borders. Structured bodice with an ornate central embroidery panel; pale silver/gray front inset bordered by teal trim running vertically. Long cape-like outer sleeves plus a matching red cloak/cape lined in teal, with patterned trim along edges and hem. Teal headscarf with a red veil drape and a jeweled headband/crown detail.",
        "Floor-length sapphire-blue silk kaftan gown with subtle jacquard pattern, fitted waist and gently flared skirt. Wide gold embroidered borders along the front opening, cuffs, and hem with arabesque motifs. Long straight sleeves with a second layer of semi-sheer chiffon over-sleeves. High neckline with a jeweled collar piece. Wide gilded waist belt with filigree medallion buckle. Matching blue veil/headscarf with gold edge trim and a jeweled forehead band with dangling pearls.",
        "Deep emerald velvet overdress with dense gold and copper embroidery on the bodice and sleeve cuffs, worn over a pale ivory inner dress that shows at the center front and hem. Cape-like outer sleeves drape from the shoulders, lined with teal satin and finished with patterned trim. Layered coin-and-gem necklace set across the chest, plus matching earrings. Broad embroidered sash belt in warm gold tones with tassel ends. Rich burgundy headscarf with turquoise accents and a beaded headpiece framing the forehead.",
        "Rose-and-ivory brocade gown with a structured bodice, square neckline, and intricate floral embroidery in gold thread across the chest and down the central panel. Full-length skirt with repeating motif bands and a wide embroidered hem. Long sleeves with ornate cuff panels and a light gauzy shawl attached at the shoulders, cascading down the arms. Silver-toned belt with engraved plates and small gemstone insets. Ivory veil with blush edging and a delicate crown-like tiara of filigree and pearls."
      ]
    }
  },
  {
    id: EraId.MODERN_EGYPT,
    name: "Modern Egypt",
    description: "Experience the vibrant energy and leisure of contemporary Egypt.",
    previewImage: "/Modern-Preview.png",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single modern Egyptian man enjoying a leisure activity in Egypt. His facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image. He wears stylish, contemporary casual clothing suitable for a sunny day out, such as a light shirt, polo, or casual jacket. The style is modern, relaxed, and photogenic. No ancient costumes. Lighting is natural, bright, and vibrant, reflecting a modern travel photography aesthetic. Background: {{BACKGROUND}}",
    singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single modern Egyptian woman enjoying a leisure activity in Egypt. Her facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image. She wears stylish, contemporary casual clothing suitable for a sunny day out, such as a fashionable summer dress, blouse, or casual chic outfit. The style is modern, relaxed, and photogenic. No ancient costumes. Lighting is natural, bright, and vibrant, reflecting a modern travel photography aesthetic. Background: {{BACKGROUND}}",
    promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} enjoying a fun day in Modern Egypt. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are dressed in stylish, contemporary casual clothing suitable for tourism or leisure activities in Egypt (e.g., light summer clothes, smart casual, travel wear). No ancient costumes. The vibe is happy, energetic, and modern. Lighting is bright, natural, and cinematic, like a high-end travel magazine feature. Background: {{BACKGROUND}}",
    backgrounds: [
      "a traditional Felucca boat sailing on the Nile River at golden hour, with the Cairo skyline and Cairo Tower visible in the distance. The water ripples gently, and the white sail catches the warm light. The atmosphere is relaxing and scenic.",
      "underwater in the Red Sea, surrounded by vibrant coral reefs and colorful tropical fish. The water is crystal clear and turquoise, with sunlight refracting through the surface. A playful interaction with a friendly sea turtle or dolphin implies a fun diving adventure.",
      "a colorful hot air balloon basket high above Luxor at sunrise, with a breathtaking view of the Valley of the Kings and lush green fields below. The sky is filled with other balloons, creating a magical and adventurous scene.",
      "the bustling Khan el-Khalili market in Old Cairo, but with a modern vibrancy. Surrounded by glowing lanterns, brass souvenirs, and colorful textiles, sipping tea at a historic cafe like El Fishawy. The atmosphere is lively, exotic, and culturally rich.",
      "the Great Sphinx of Giza, but from a modern tourist perspective, perhaps with a camel nearby and the pyramids in the background. The sky is bright blue, and the scene is iconic and grand.",
    ],
    stamps: [
      "/Stamps/Modern-Egypt/1.png"
    ]
  }
];
