import { EraData, EraId } from './types';

export const ERAS: EraData[] = [
  {
    id: EraId.OLD_EGYPT,
    name: "Old Kingdom",
    description: "Journey back to the time of Pharaohs and Pyramids (c. 2686–2181 BC).",
    previewImage: "/Old-Egypt-Preview.jpg", // Fallback placeholder
    promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing ancient Egyptian pharaonic outfits. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are fully dressed in regal pharaonic costumes with elegant gold and deep turquoise details and subtle hieroglyphic patterns. Lighting is warm and cinematic with realistic shadows and natural depth of field. The final image should look like a modern professional photoshoot with a strong pharaonic theme. No added accessories, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of an Ancient Egyptian pharaoh standing authoritatively. He wears a golden Nemes headdress, ceremonial false beard, and an ornate blue-and-gold collar, with matching bracelets and royal regalia. His makeup is authentic Ancient Egyptian male style: black kohl around the eyes from galena or stibnite, green malachite eyeshadow, subtle red ochre on lips and cheeks, henna accents on nails or beard, and natural lip balm. His facial features, skin tone, expression, and hair color are fully preserved and unchanged, reflecting his unique identity and royal presence. Background: {{BACKGROUND}}",
    singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of an Ancient Egyptian queen standing confidently. She wears a flowing white linen kalasiris gown with subtle translucency and refined gold trim that catches the light. She wears an ornate beaded queen-style headdress with intricate patterns, complemented by gold and gemstone bracelets, a broad collar, and ceremonial jewelry. Her makeup is authentic Ancient Egyptian: bold black kohl eyeliner and mascara from galena or stibnite, green malachite eyeshadow, subtle copper-gold highlights, red ochre on lips and cheeks, henna on nails, and naturally glowing, moisturized skin. Her facial features, skin tone, expression, and hair color are fully preserved and unchanged, reflecting her individuality. Background: {{BACKGROUND}}",
    backgrounds: [
      "the majestic Philae Temple beside the Nile River, with stone columns, statues of gods and goddesses, lush palm trees, flowering plants, soft mist rising from the river, and reflections on the water. The sky glows with warm golden-hour light, cinematic god rays, subtle cosmic particles, shallow depth of field, realistic shadows, and atmospheric fog. Photorealistic, majestic, sacred, and timeless.",
      "the Great Pyramids of Giza at sunset, with the Sphinx visible in the hazy distance. The desert sand glows with a golden hue, and the sky is a dramatic gradient of orange and purple. The atmosphere is ancient, mysterious, and grand, with a sense of eternal history.",
      "the massive columns of the Karnak Temple Hypostyle Hall, illuminated by torchlight and shafts of sunlight piercing through the stone roof. The walls are covered in hieroglyphs and relief carvings. The atmosphere is mystical, spiritual, and awe-inspiring.",
      "a luxurious royal palace interior with painted soaring columns, golden artifacts, and an open balcony overlooking the Nile. The walls are adorned with colorful frescoes of daily life and mythology. The floor is polished stone, reflecting the warm light of oil lamps."
    ]
  },
  {
    id: EraId.COPTIC_EGYPT,
    name: "Coptic Era",
    description: "Experience the unique art and spirituality of late antique Egypt (c. 3rd–7th century AD).",
    previewImage: "/Coptic-Preview.jpg",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian man from the Coptic era of late antiquity, standing calmly and facing the camera. His facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.He wears an authentic Coptic linen tunic (kolothos) in natural off-white or beige tones, with historically accurate tapestry-woven clavi and orbiculi featuring subtle geometric or floral motifs in muted red, indigo, or ochre. The fabric appears hand-woven with visible linen texture and natural dyes, fitting modestly and realistically.His grooming is natural and understated: short dark hair, optional trimmed beard, and minimal traditional kohl lightly defining the eyes in a historically accurate manner. No crowns, jewelry, pharaonic elements, or modern accessories.Lighting is warm and soft, with realistic shadows and shallow depth of field, resembling a modern professional portrait while maintaining an authentic ancient Coptic Egyptian atmosphere. Skin texture is natural and lifelike.Background: {{BACKGROUND}}"
    , singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian woman from the Coptic era of late antiquity, standing gracefully and facing the camera. Her facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.She wears an authentic Coptic linen tunic in natural linen or soft earth tones, decorated with tapestry-woven clavi and orbiculi featuring delicate geometric or floral patterns in muted red, indigo, or gold-ochre hues. A historically accurate light mantle or veil may be draped naturally over the shoulders or head, consistent with early Christian Egyptian customs. The fabric appears hand-woven, with visible linen texture and natural dyes.Her appearance is modest and natural: minimal makeup, softly defined eyes with subtle traditional kohl, natural lips, and historically appropriate hairstyle partially covered by the veil. No jewelry beyond simple, era-accurate details; no crowns or modern elements.Lighting is warm and soft with realistic shadows and gentle depth of field, creating a refined modern portrait aesthetic grounded in authentic ancient Coptic Egyptian styling. Skin texture is natural and realistic.Background: {{BACKGROUND}}"
    , promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing traditional Coptic Egyptian clothing from late antiquity. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression. All individuals are dressed in authentic Coptic garments, including woven linen tunics (kolothos) with tapestry-woven decorative clavi and orbiculi, geometric and floral motifs, earthy beige and natural linen tones, and hand-embroidered borders. Optional shawls, mantles, or veils may appear depending on gender and era, but must remain historically accurate to early Christian Egypt. Textures should show real linen weave and natural dyes.Lighting is warm and soft with realistic shadows and natural depth of field, creating the look of a modern professional photoshoot with a strong ancient Coptic Egyptian theme. No added accessories outside historical context, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    backgrounds: [
      "an ancient Coptic monastery courtyard with limestone walls and desert plants. The sunlight is bright and harsh, casting deep shadows. The atmosphere is peaceful, ascetic, and timeless.",
      "a historic street in Old Cairo (Masr el Adima) with stone arches and hanging oil lamps. The narrow alleyway is bustling with subtle activity, although the focus remains on the subjects. The textures of the stone and wood are weathered and authentic.",
      "the interior of an ancient stone church with faded frescoes and warm candlelight. The air is thick with the scent of incense. The light is soft, golden, and mysterious, illuminating the faces of the subjects.",
      "a serene desert landscape near the Red Sea monasteries, with palm trees and a vast open sky. The sand is golden-red, and the mountains in the distance are rugged and majestic. The feeling is one of isolation and spiritual purity."
    ]
  },
  {
    id: EraId.ISLAMIC_EGYPT,
    name: "Islamic Golden Age",
    description: "Step into the vibrant culture of medieval Cairo (c. 7th–16th century AD).",
    previewImage: "./Islamic-Preview.jpg",
    singleMalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian man from the early Islamic period, standing calmly and facing the camera. His facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.He wears historically accurate early Islamic Egyptian clothing: a loose-fitting linen or cotton tunic (qamis) in soft white or cream tones, layered with a simple wool or silk outer robe featuring subtle embroidered hems or woven geometric or vegetal motifs typical of early Islamic Egyptian textiles. A modest turban or cloth head wrap may be worn naturally, appropriate to the era and social context. Decorative tiraz-style bands with restrained Kufic-inspired ornamental patterns may appear on the sleeves or chest, remaining subtle and authentic.His grooming is natural and modest: short or medium dark hair, optional neatly kept beard, and no modern styling. No crowns, no jewelry outside historical context, and no contemporary accessories.Lighting is warm and cinematic with realistic shadows and natural depth of field, creating a modern professional portrait aesthetic grounded in early Islamic Egyptian culture. Skin texture is natural and lifelike.Background: {{BACKGROUND}}",
    singleFemalePrompt: "A hyper-realistic, high-resolution, portrait-oriented photo of a single Egyptian woman from the early Islamic period, standing gracefully and facing the camera. Her facial features, proportions, skin tone, age, expression, and overall identity are fully preserved and unchanged from the reference image.She wears historically accurate early Islamic Egyptian attire: a long, loose-fitting linen or cotton tunic in soft neutral or earth tones, layered with a lightweight outer robe or mantle featuring embroidered hems and woven geometric or vegetal motifs common in early Islamic Egyptian textiles. A simple veil or headscarf is draped naturally over the hair and shoulders, appropriate to the period and social setting. Subtle tiraz-style decorative bands with Kufic-inspired ornamental patterns may appear on the garment edges, remaining understated and historically accurate.Her appearance is modest and natural: minimal makeup, softly defined eyes, natural lips, and historically appropriate hairstyle covered by the veil. No modern accessories or jewelry beyond simple, era-appropriate details.Lighting is warm and cinematic with realistic shadows and gentle depth of field, producing a refined modern portrait feel while preserving authentic early Islamic Egyptian aesthetics. Skin texture is natural and realistic.Background: {{BACKGROUND}}",
    promptStyle: "A hyper-realistic, high-resolution portrait-oriented photo of {{GROUP_DESCRIPTION}} standing together, wearing traditional clothing from early Islamic Egypt. Each person’s appearance must accurately match their reference photo, fully preserving identity, natural skin tone, ethnic features, gender, age, proportions, and expression.All individuals are dressed in historically accurate garments such as loose-fitting linen or cotton tunics (qamis), decorated wool or silk outer robes, embroidered hems, and woven geometric or vegetal motifs common in early Islamic Egyptian textiles. Clothing may include long-sleeved tunics, layered cloaks, turbans, veils, simple headscarves, or decorative tiraz bands with Kufic-inspired ornamental patterns, depending on gender and social context — all staying authentic to early Islamic Egypt. Colors should reflect natural dyes: soft whites, creams, deep blues, earthy reds, greens, and muted tones.Lighting is warm and cinematic with realistic shadows and natural depth of field, creating the look of a modern professional photoshoot with an early Islamic Egyptian cultural theme. No added accessories outside historical context, no distortion, and no cartoon style — everything must appear natural, cohesive, and true to the original individuals. Background: {{BACKGROUND}}",
    backgrounds: [
      "the vibrant Muizz Street in medieval Cairo, lined with Mamluk architecture and stone minarets. The street is paved with stone and lined with historic buildings. The atmosphere is bustling and lively, with a sense of history and culture.",
      "the courtyard of the Ibn Tulun Mosque, featuring geometric stone arches and a central ablution fountain. The light is soft and diffused, creating a serene and spiritual atmosphere. The architecture is grand and imposing.",
      "a bustling medieval fabric market (Khan el-Khalili) with hanging colorful lamps and carpets. The stalls are filled with textiles, spices, and crafts. The lighting is warm and inviting, with a sense of exotic mystery.",
      "a royal Mamluk palace balcony with intricate mashrabiya woodwork and a view of the Cairo citadel. The view is breathtaking, overlooking the city and the Nile. The atmosphere is luxurious and regal."
    ]
  }
];
